version: '3'

services:

  nginx:
    image: nginx:alpine
    volumes:
      - ./www:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/nginx/certs:/etc/nginx/certs
    ports:
      - ${SERVER_PORT}:80
      - 443:443

  # app:
  #   build:
  #     context: .
  #     args:
  #       - tag=${PHP_TAG}
  #       - uid=${SYSTEM_UID}
  #     dockerfile: ./docker/php-fpm/Dockerfile
  #   volumes:
  #     - ./www:/var/www
  #     - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
  #   working_dir: /var/www
  #   depends_on:
  #     - nginx
      # - db

  # db:
  #   image: mysql:${DB_VERSION}
  #   platform: linux/x86_64
  #   command: --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - ${DB_PORT}:3306
  #   volumes:
  #     - ./docker/db/data:/var/lib/database
  #   environment:
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  # redis:
  #   image: redis:alpine
  #   command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
  #   volumes:
  #     - ./docker/redis:/data
  #   ports:
  #     - ${REDIS_PORT}:6379

  db:
    image: mysql:${DB_VERSION}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./docker/db/data:/var/lib/database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
    depends_on:
      - db